#! /bin/sh


de=$(echo $DESKTOP_SESSION)

if [[ "$de" != "" ]]
  then
    echo "$de"
  else
    picom --config ~/.config/picom.conf
fi



pgrep -x sxhkd > /dev/null || sxhkd &
bash ~/.config/polybar/launch.sh &
feh --bg-fill --randomize ~/wallpapers/*
#for random change after 1h
#while true ; do feh --bg-fill --randomize ~/wallpapers/* ; sleep 3600 ; done &

xsetroot -cursor_name left_ptr 

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

### Setting for individual app

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Firefox desktop='^2'
bspc rule -a kitty desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
